// GENERATED by the boss from the live Supabase schema — never hand-edit.
// Regenerate: Supabase MCP generate_typescript_types (or `npx supabase gen types typescript --linked` once linked).
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      alerts: {
        Row: {
          acknowledged_at: string | null
          acknowledged_by: string | null
          created_at: string
          guardrail: string
          id: string
          patient_id: string
          prescription_id: string | null
          reason: string
          run_id: string | null
        }
        Insert: {
          acknowledged_at?: string | null
          acknowledged_by?: string | null
          created_at?: string
          guardrail: string
          id?: string
          patient_id: string
          prescription_id?: string | null
          reason: string
          run_id?: string | null
        }
        Update: {
          acknowledged_at?: string | null
          acknowledged_by?: string | null
          created_at?: string
          guardrail?: string
          id?: string
          patient_id?: string
          prescription_id?: string | null
          reason?: string
          run_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "alerts_acknowledged_by_fkey"
            columns: ["acknowledged_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "alerts_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "alerts_prescription_id_fkey"
            columns: ["prescription_id"]
            isOneToOne: false
            referencedRelation: "depletion_forecast"
            referencedColumns: ["prescription_id"]
          },
          {
            foreignKeyName: "alerts_prescription_id_fkey"
            columns: ["prescription_id"]
            isOneToOne: false
            referencedRelation: "prescriptions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "alerts_run_id_fkey"
            columns: ["run_id"]
            isOneToOne: false
            referencedRelation: "runs"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_log: {
        Row: {
          action: Database["public"]["Enums"]["audit_action"]
          actor_id: string | null
          actor_role: Database["public"]["Enums"]["audit_actor"]
          after: Json | null
          at: string
          before: Json | null
          id: number
          patient_id: string
          row_id: string
          run_id: string | null
          table_name: string
        }
        Insert: {
          action: Database["public"]["Enums"]["audit_action"]
          actor_id?: string | null
          actor_role: Database["public"]["Enums"]["audit_actor"]
          after?: Json | null
          at?: string
          before?: Json | null
          id?: never
          patient_id: string
          row_id: string
          run_id?: string | null
          table_name: string
        }
        Update: {
          action?: Database["public"]["Enums"]["audit_action"]
          actor_id?: string | null
          actor_role?: Database["public"]["Enums"]["audit_actor"]
          after?: Json | null
          at?: string
          before?: Json | null
          id?: never
          patient_id?: string
          row_id?: string
          run_id?: string | null
          table_name?: string
        }
        Relationships: [
          {
            foreignKeyName: "audit_log_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audit_log_run_id_fkey"
            columns: ["run_id"]
            isOneToOne: false
            referencedRelation: "runs"
            referencedColumns: ["id"]
          },
        ]
      }
      doctor_patients: {
        Row: {
          created_at: string
          doctor_id: string
          id: string
          patient_id: string
        }
        Insert: {
          created_at?: string
          doctor_id: string
          id?: string
          patient_id: string
        }
        Update: {
          created_at?: string
          doctor_id?: string
          id?: string
          patient_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "doctor_patients_doctor_id_fkey"
            columns: ["doctor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "doctor_patients_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      doses: {
        Row: {
          answered_at: string | null
          created_at: string
          id: string
          original_at: string | null
          prescription_id: string
          scheduled_at: string
          status: Database["public"]["Enums"]["dose_status"]
        }
        Insert: {
          answered_at?: string | null
          created_at?: string
          id?: string
          original_at?: string | null
          prescription_id: string
          scheduled_at: string
          status?: Database["public"]["Enums"]["dose_status"]
        }
        Update: {
          answered_at?: string | null
          created_at?: string
          id?: string
          original_at?: string | null
          prescription_id?: string
          scheduled_at?: string
          status?: Database["public"]["Enums"]["dose_status"]
        }
        Relationships: [
          {
            foreignKeyName: "doses_prescription_id_fkey"
            columns: ["prescription_id"]
            isOneToOne: false
            referencedRelation: "depletion_forecast"
            referencedColumns: ["prescription_id"]
          },
          {
            foreignKeyName: "doses_prescription_id_fkey"
            columns: ["prescription_id"]
            isOneToOne: false
            referencedRelation: "prescriptions"
            referencedColumns: ["id"]
          },
        ]
      }
      interactions: {
        Row: {
          added_by: string | null
          created_at: string
          id: string
          ingredient_a: string
          ingredient_b: string
          min_hours_apart: number
          source: string
        }
        Insert: {
          added_by?: string | null
          created_at?: string
          id?: string
          ingredient_a: string
          ingredient_b: string
          min_hours_apart: number
          source: string
        }
        Update: {
          added_by?: string | null
          created_at?: string
          id?: string
          ingredient_a?: string
          ingredient_b?: string
          min_hours_apart?: number
          source?: string
        }
        Relationships: [
          {
            foreignKeyName: "interactions_added_by_fkey"
            columns: ["added_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      medications: {
        Row: {
          catch_up_window_h: number | null
          created_at: string
          id: string
          ingredient: string
          is_time_critical: boolean
          justification: Json
          min_gap_h: number | null
          verification: Database["public"]["Enums"]["med_verification"]
          verified_at: string | null
          verified_by: string | null
        }
        Insert: {
          catch_up_window_h?: number | null
          created_at?: string
          id?: string
          ingredient: string
          is_time_critical?: boolean
          justification: Json
          min_gap_h?: number | null
          verification?: Database["public"]["Enums"]["med_verification"]
          verified_at?: string | null
          verified_by?: string | null
        }
        Update: {
          catch_up_window_h?: number | null
          created_at?: string
          id?: string
          ingredient?: string
          is_time_critical?: boolean
          justification?: Json
          min_gap_h?: number | null
          verification?: Database["public"]["Enums"]["med_verification"]
          verified_at?: string | null
          verified_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "medications_verified_by_fkey"
            columns: ["verified_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      prescription_drafts: {
        Row: {
          accepted_at: string | null
          confidence: Json | null
          created_at: string
          extracted: Json
          id: string
          patient_id: string
          source_image: string | null
        }
        Insert: {
          accepted_at?: string | null
          confidence?: Json | null
          created_at?: string
          extracted: Json
          id?: string
          patient_id: string
          source_image?: string | null
        }
        Update: {
          accepted_at?: string | null
          confidence?: Json | null
          created_at?: string
          extracted?: Json
          id?: string
          patient_id?: string
          source_image?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "prescription_drafts_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      prescriptions: {
        Row: {
          brand_dispensed: string | null
          created_at: string
          dispense_date: string | null
          doctor_id: string | null
          dose_per_administration: number
          dosing_pattern: Database["public"]["Enums"]["dosing_pattern"]
          drug_name_brand: string | null
          drug_name_generic: string
          duration_days: number
          food_timing: string | null
          frequency_per_day: number
          id: string
          indication: string | null
          notes: string | null
          patient_id: string
          route: Database["public"]["Enums"]["route_of_admin"]
          source: Database["public"]["Enums"]["rx_source"]
          source_facility: string | null
          source_sector: Database["public"]["Enums"]["rx_sector"] | null
          start_date: string
          strength_unit: Database["public"]["Enums"]["strength_unit"]
          strength_value: number
          total_quantity_dispensed: number | null
          units_per_package: number | null
          updated_at: string
        }
        Insert: {
          brand_dispensed?: string | null
          created_at?: string
          dispense_date?: string | null
          doctor_id?: string | null
          dose_per_administration: number
          dosing_pattern?: Database["public"]["Enums"]["dosing_pattern"]
          drug_name_brand?: string | null
          drug_name_generic: string
          duration_days: number
          food_timing?: string | null
          frequency_per_day: number
          id?: string
          indication?: string | null
          notes?: string | null
          patient_id: string
          route?: Database["public"]["Enums"]["route_of_admin"]
          source?: Database["public"]["Enums"]["rx_source"]
          source_facility?: string | null
          source_sector?: Database["public"]["Enums"]["rx_sector"] | null
          start_date?: string
          strength_unit: Database["public"]["Enums"]["strength_unit"]
          strength_value: number
          total_quantity_dispensed?: number | null
          units_per_package?: number | null
          updated_at?: string
        }
        Update: {
          brand_dispensed?: string | null
          created_at?: string
          dispense_date?: string | null
          doctor_id?: string | null
          dose_per_administration?: number
          dosing_pattern?: Database["public"]["Enums"]["dosing_pattern"]
          drug_name_brand?: string | null
          drug_name_generic?: string
          duration_days?: number
          food_timing?: string | null
          frequency_per_day?: number
          id?: string
          indication?: string | null
          notes?: string | null
          patient_id?: string
          route?: Database["public"]["Enums"]["route_of_admin"]
          source?: Database["public"]["Enums"]["rx_source"]
          source_facility?: string | null
          source_sector?: Database["public"]["Enums"]["rx_sector"] | null
          start_date?: string
          strength_unit?: Database["public"]["Enums"]["strength_unit"]
          strength_value?: number
          total_quantity_dispensed?: number | null
          units_per_package?: number | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "prescriptions_doctor_id_fkey"
            columns: ["doctor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "prescriptions_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          civil_id: string | null
          created_at: string
          full_name: string
          id: string
          role: Database["public"]["Enums"]["user_role"]
        }
        Insert: {
          civil_id?: string | null
          created_at?: string
          full_name: string
          id: string
          role?: Database["public"]["Enums"]["user_role"]
        }
        Update: {
          civil_id?: string | null
          created_at?: string
          full_name?: string
          id?: string
          role?: Database["public"]["Enums"]["user_role"]
        }
        Relationships: []
      }
      runs: {
        Row: {
          doses_checked: number | null
          finished_at: string | null
          id: string
          kind: Database["public"]["Enums"]["run_kind"]
          patient_id: string
          result: Json | null
          started_at: string
          status: Database["public"]["Enums"]["run_status"]
        }
        Insert: {
          doses_checked?: number | null
          finished_at?: string | null
          id?: string
          kind: Database["public"]["Enums"]["run_kind"]
          patient_id: string
          result?: Json | null
          started_at?: string
          status?: Database["public"]["Enums"]["run_status"]
        }
        Update: {
          doses_checked?: number | null
          finished_at?: string | null
          id?: string
          kind?: Database["public"]["Enums"]["run_kind"]
          patient_id?: string
          result?: Json | null
          started_at?: string
          status?: Database["public"]["Enums"]["run_status"]
        }
        Relationships: [
          {
            foreignKeyName: "runs_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      depletion_forecast: {
        Row: {
          dispense_date: string | null
          drug_name_generic: string | null
          patient_id: string | null
          prescription_id: string | null
          runs_out_on: string | null
        }
        Insert: {
          dispense_date?: string | null
          drug_name_generic?: string | null
          patient_id?: string | null
          prescription_id?: string | null
          runs_out_on?: never
        }
        Update: {
          dispense_date?: string | null
          drug_name_generic?: string | null
          patient_id?: string | null
          prescription_id?: string | null
          runs_out_on?: never
        }
        Relationships: [
          {
            foreignKeyName: "prescriptions_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      generate_doses: { Args: { p_prescription: string }; Returns: number }
      is_doctor: { Args: never; Returns: boolean }
      is_linked_doctor: { Args: { p_patient: string }; Returns: boolean }
    }
    Enums: {
      audit_action: "insert" | "update" | "delete"
      audit_actor: "patient" | "doctor" | "agent" | "system"
      dose_status: "due" | "taken" | "skipped" | "missed" | "rescheduled"
      dosing_pattern: "daily" | "alternate_day" | "weekly" | "as_needed"
      med_verification: "verified" | "unverified"
      route_of_admin: "oral" | "injection" | "syrup" | "inhaler" | "topical"
      run_kind:
        | "check_doses"
        | "profile_medication"
        | "screen_interactions"
        | "extract_prescription"
      run_status: "queued" | "running" | "done" | "failed"
      rx_sector: "public" | "private"
      rx_source: "jurah_doctor" | "imported" | "patient_entered" | "extracted"
      strength_unit: "mg" | "mcg" | "g" | "ml" | "iu" | "percent"
      user_role: "patient" | "doctor"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      audit_action: ["insert", "update", "delete"],
      audit_actor: ["patient", "doctor", "agent", "system"],
      dose_status: ["due", "taken", "skipped", "missed", "rescheduled"],
      dosing_pattern: ["daily", "alternate_day", "weekly", "as_needed"],
      med_verification: ["verified", "unverified"],
      route_of_admin: ["oral", "injection", "syrup", "inhaler", "topical"],
      run_kind: [
        "check_doses",
        "profile_medication",
        "screen_interactions",
        "extract_prescription",
      ],
      run_status: ["queued", "running", "done", "failed"],
      rx_sector: ["public", "private"],
      rx_source: ["jurah_doctor", "imported", "patient_entered", "extracted"],
      strength_unit: ["mg", "mcg", "g", "ml", "iu", "percent"],
      user_role: ["patient", "doctor"],
    },
  },
} as const
