'use server'

import { revalidatePath } from 'next/cache'
import { createClient } from '@/lib/supabase/server'
import { prescriptionAddSchema, firstIssue, type IssueCode } from './schema'

/**
 * D21: the patient is the aggregation point. The client never chooses `source`
 * or `doctor_id` — this is always a patient-entered row. Doses are generated by
 * a DB trigger from the dosing pattern; nothing clinical is computed here (D23).
 */
export async function addPrescription(input: unknown): Promise<{ ok: true; id: string } | { ok: false; error: string; path?: string; code?: IssueCode }> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { ok: false, error: 'Not signed in.' }

  const parsed = prescriptionAddSchema.safeParse(input)
  if (!parsed.success) {
    const issue = firstIssue(parsed.error)
    return { ok: false, error: 'invalid', path: issue.path, code: issue.code }
  }

  const { data, error } = await supabase
    .from('prescriptions')
    .insert({
      patient_id: user.id,
      source: 'patient_entered',
      ...parsed.data,
    })
    .select('id')
    .single()

  if (error) return { ok: false, error: error.message }

  revalidatePath('/prescriptions')
  revalidatePath('/dashboard')
  return { ok: true, id: data.id }
}
